export const SET_EDIT_SCENE_TITLE = 'SET_EDIT_SCENE_TITLE';
export const SET_SCENE_ID = 'SET_SCENE_ID';
export const SET_DATA_SCENE = 'SET_DATA_SCENE';
export const CHANGE_MODAL = 'CHANGE_MODAL';
export const CHANGE_ROTATION = 'CHANGE_ROTATION';
